default: &default
  adapter: postgresql
  host: ec2-54-225-168-181.compute-1.amazonaws.com
  username: fffyzptdsqaqyd
  password: uMpy4-IMexa6EgD6sF5h39W5hv
  pool: 5

development:
  <<: *default
  database: ddh3nlkdmbo8k
test:
  <<: *default
  database: ddh3nlkdmbo8k

production:
  <<: *default
  database: ddh3nlkdmbo8k
